export const STRINGS = {
    en: {
        'common.delete': 'Delete',
        'common.resetDefaults': 'Reset to defaults',

        'core.intro': 'A set of quality-of-life tools. Every module can be switched off with its toggle.',
        'core.language': 'Language',
        'core.languageAuto': 'Automatic',
        'core.enableModule': 'Enable / disable module',

        // Panic
        'panic.title': 'Dad Came (panic mode)',
        'panic.desc': 'One tap hides character pictures and backgrounds and blacks out "interesting" sentences like a declassified document. Tap again to restore everything. Chat data is never modified.',
        'panic.menuOn': 'Dad Came!',
        'panic.menuOff': 'All clear — restore',
        'panic.toggleNow': 'Toggle now',
        'panic.sectionTriggers': 'How to trigger',
        'panic.hotkey': 'Hotkey',
        'panic.hotkeyHint': 'Click the field and press a key combination. Works with any keyboard layout.',
        'panic.hotkeyPlaceholder': 'Click and press keys',
        'panic.doubleEscape': 'Double press Esc',
        'panic.floatingButton': 'Floating quick button',
        'panic.floatingButtonHint': 'A small draggable button on top of the page — the fastest way on a phone. Drag it anywhere.',
        'panic.threeFingerTap': 'Three-finger tap (touch screens)',
        'panic.threeFingerTapHint': 'Touch the screen with three fingers at once.',
        'panic.rememberState': 'Stay hidden after page reload',
        'panic.rememberStateHint': 'If the page is reloaded while hidden, it opens hidden.',
        'panic.sectionImages': 'Pictures',
        'panic.hideImages': 'Hide avatars, sprites and chat images',
        'panic.hideBackground': 'Hide chat background',
        'panic.imageMode': 'How to hide',
        'panic.imageModeHide': 'Remove completely (neutral placeholder)',
        'panic.imageModeBlur': 'Heavy blur',
        'panic.hidePanels': 'Hide open side panels',
        'panic.hidePanelsHint': 'Character list, character card, World Info, floating windows. They come back exactly as they were.',
        'panic.sectionText': 'Text redaction',
        'panic.redactText': 'Black out matching text',
        'panic.redactMode': 'What to black out',
        'panic.modeSentence': 'Whole sentence with a keyword',
        'panic.modeWord': 'Only the keyword itself',
        'panic.modeParagraph': 'Whole paragraph',
        'panic.keywords': 'Keywords',
        'panic.keywordsHint': 'One per line or comma-separated. word — the word and its forms; word* — anything starting with it; "word" — exactly this word; several words — a phrase; /regex/ — regular expression; # — comment.',
        'panic.keywordsCount': 'Active entries: {count}',
        'panic.keywordsErrors': 'Active entries: {count}. Invalid: {errors}',
        'panic.smartForms': 'Match word forms automatically',
        'panic.smartFormsHint': 'поцелуй also finds поцелуя / поцелуями, kiss finds kisses / kissed.',
        'panic.redactReasoning': 'Also black out reasoning (thinking) blocks',
        'panic.redactNames': 'Black out character and persona names',
        'panic.redactNamesHint': 'Names in the text and in message headers become black bars too.',
        'panic.noise': 'Extra random redaction',
        'panic.noiseHint': 'Also black out a share of ordinary sentences, so the page looks like a real redacted file and the context is harder to guess.',
        'panic.barColor': 'Bar color',
        'panic.peekOnHold': 'Press and hold a bar to peek',
        'panic.peekOnHoldHint': 'The text is shown only while you hold your finger or mouse button on it.',
        'panic.sectionExtras': 'Extras',
        'panic.blurInput': 'Blur the message input',
        'panic.pauseMedia': 'Pause music, video and TTS (resume afterwards)',
        'panic.stopGeneration': 'Stop generation',
        'panic.disguiseTab': 'Disguise the browser tab (title and icon)',
        'panic.disguiseTitle': 'Tab title while hidden',
        'panic.defaultTitle': 'Untitled document',
        'panic.slashHelp': 'Toggles panic mode ("Dad Came"). Argument: on, off or toggle.',

        // Navigator
        'nav.title': 'Chat search & bookmarks',
        'nav.desc': 'Search the whole chat, including old messages that are not loaded and alternative swipes. Bookmark important messages and jump to them in one tap.',
        'nav.menuSearch': 'Search in chat',
        'nav.menuPins': 'Bookmarks',
        'nav.searchTitle': 'Search in chat',
        'nav.searchPlaceholder': 'Words or "an exact phrase"…',
        'nav.searchHint': 'Type to search through all {count} messages. Several words — all must be present.',
        'nav.filter.all': 'All',
        'nav.filter.user': 'Mine',
        'nav.filter.char': 'Character',
        'nav.wholeWords': 'Whole words',
        'nav.includeSwipes': 'Swipes',
        'nav.includeReasoning': 'Reasoning',
        'nav.found': 'Found: {total}',
        'nav.foundMore': 'Found: {total} (showing {shown})',
        'nav.nothing': 'Nothing found',
        'nav.swipeOf': 'swipe {n}/{total}',
        'nav.reasoning': 'reasoning',
        'nav.swipeHint': 'The match is in swipe #{n} of this message.',
        'nav.toTop': 'To the start',
        'nav.toBottom': 'To the end',
        'nav.goto': 'Go',
        'nav.gotoInvalid': 'Enter a message number from 0 to {max}.',
        'nav.searchHotkey': 'Search hotkey',
        'nav.showMessageButton': 'Bookmark button on messages',
        'nav.showMessageButtonHint': 'A ☆ button appears in the message actions (the "…" menu).',
        'nav.pinButton': 'Bookmark',
        'nav.pinsTitle': 'Bookmarks in this chat',
        'nav.pinsCount': 'Bookmarks: {count}',
        'nav.pinsEmpty': 'No bookmarks yet. Use ☆ in the message actions or the button below.',
        'nav.pinsHint': 'Bookmarks are stored inside the chat file and survive deleting messages above them.',
        'nav.pinLast': 'Bookmark the last message',
        'nav.pinNotePlaceholder': 'Note…',
        'nav.pinBroken': 'Message not found (deleted?)',
        'nav.pinAdded': 'Message #{id} bookmarked',
        'nav.pinRemoved': 'Bookmark #{id} removed',
        'nav.slashSearch': 'Opens the chat search. Optional argument: the query.',
        'nav.slashPin': 'Toggles a bookmark on a message. Argument: message id (default: the last message).',
        'nav.slashPins': 'Opens the list of bookmarks in the current chat.',

        // Drafts
        'drafts.title': 'Drafts & input history',
        'drafts.desc': 'What you are typing is saved for every chat and survives reloads, closed tabs and switching chats. Sent messages go to a history you can reuse.',
        'drafts.menu': 'Input history',
        'drafts.restored': 'Draft restored',
        'drafts.perChat': 'Separate draft for every chat',
        'drafts.perChatHint': 'When you switch chats, the input shows the draft of the opened chat.',
        'drafts.notifyRestore': 'Show a notice when a draft is restored',
        'drafts.historyHotkeys': 'Alt + ↑ / ↓ cycles through sent messages',
        'drafts.historyHotkeysHint': 'Works inside the message input, like a terminal history.',
        'drafts.historySize': 'History size',
        'drafts.historyTitle': 'Input history',
        'drafts.historyHint': 'Tap an entry to put it into the message input.',
        'drafts.lastDraft': 'Last draft of this chat',
        'drafts.lastDraftMeta': 'Restore if you erased it by accident',
        'drafts.sent': 'Sent messages ({count})',
        'drafts.empty': 'Nothing here yet.',
        'drafts.clearHistory': 'Clear history',
        'drafts.slashHelp': 'Opens the input history.',

        // Slop radar
        'slop.title': 'Cliché radar',
        'slop.desc': 'Underlines worn-out AI phrases ("shivers down her spine", "barely above a whisper", "мурашки по коже"…) in replies, counts them per chat and can ask the model to avoid the ones it overuses.',
        'slop.menu': 'Cliché radar',
        'slop.markTitle': 'Cliché',
        'slop.highlight': 'Underline clichés in replies',
        'slop.style': 'Style',
        'slop.styleWavy': 'Wavy underline',
        'slop.styleDotted': 'Dotted underline',
        'slop.styleBackground': 'Background marker',
        'slop.color': 'Color',
        'slop.phrases': 'Phrases',
        'slop.phrasesHint': 'Same syntax as keywords: word, word*, "exact", phrases and /regex/.',
        'slop.phrasesCount': 'Active entries: {count}',
        'slop.phrasesErrors': 'Active entries: {count}. Invalid: {errors}',
        'slop.sectionInject': 'Anti-cliché instruction',
        'slop.injectAvoid': 'Automatically ask the model to avoid its top clichés',
        'slop.injectAvoidHint': 'Adds a short system note with the most frequent clichés of this chat to the prompt. Updated after every reply.',
        'slop.injectTop': 'How many phrases to include',
        'slop.injectScope': 'Analyze the last N replies',
        'slop.injectDepth': 'Insertion depth (0 = at the very end)',
        'slop.injectTemplate': 'Instruction template',
        'slop.injectTemplateHint': '{phrases} is replaced with the list.',
        'slop.statsTitle': 'Cliché radar — this chat',
        'slop.kpiIndex': 'per 1000 words',
        'slop.kpiIndexHint': 'Clichés per 1000 words of AI replies',
        'slop.kpiHits': 'clichés',
        'slop.kpiMessages': 'replies',
        'slop.kpiWords': 'words',
        'slop.gradeClean': 'Clean prose — nice!',
        'slop.gradeOk': 'Tolerable',
        'slop.gradeMany': 'Quite a lot of clichés',
        'slop.gradeSlop': 'Slop alert!',
        'slop.gradeTooLittle': 'Too little text for a verdict yet',
        'slop.chartTitle': 'Clichés in recent replies (tap a bar to jump)',
        'slop.topTitle': 'Most frequent',
        'slop.noHits': 'No clichés found.',
        'slop.copyInstruction': 'Copy as an instruction',
        'slop.copied': 'Copied — paste it into Author\'s Note or the system prompt.',
        'slop.statsHint': 'Only AI replies are counted. Edit the phrase list in the extension settings.',
        'slop.slashHelp': 'Opens cliché statistics for the current chat and returns clichés per 1000 words.',

        // Notifier
        'notifier.title': 'Reply notifications & wake lock',
        'notifier.desc': 'A chime, vibration or blinking tab when the reply is ready, and the screen stays on while the model is writing — the phone will not fall asleep and cut the stream.',
        'notifier.readyTitle': '{name}: reply is ready',
        'notifier.readyBody': 'Open the chat to read it',
        'notifier.test': 'Test',
        'notifier.onlyWhenHidden': 'Only when the tab is in background',
        'notifier.onlyWhenHiddenHint': 'Otherwise notifies after every reply.',
        'notifier.sound': 'Sound',
        'notifier.volume': 'Volume',
        'notifier.vibrate': 'Vibration',
        'notifier.vibrateHint': 'Phones only; browsers vibrate only while the page is visible.',
        'notifier.flashTitle': 'Blink the tab title',
        'notifier.systemNotification': 'System notification',
        'notifier.systemNotificationHint': 'Asks for permission. Works on desktop browsers; Android Chrome may not show it without an installed app.',
        'notifier.showPreview': 'Show the reply text in the notification',
        'notifier.minDuration': 'Minimum generation time, seconds',
        'notifier.minDurationHint': 'Quick replies do not trigger a notification.',
        'notifier.sectionWake': 'Keep the screen on',
        'notifier.wakeLock': 'Screen wake lock',
        'notifier.wakeGeneration': 'While a reply is being generated',
        'notifier.wakeAlways': 'Always while the tab is open',
        'notifier.wakeOff': 'Off',
        'notifier.wakeHint': 'Needs HTTPS or localhost / 127.0.0.1.',
        'notifier.wakeUnsupported': 'This browser does not support Wake Lock.',

        // Performance
        'perf.title': 'Performance (phones)',
        'perf.desc': 'Makes SillyTavern lighter on phones without changing how it looks: off-screen messages are not rendered, huge backgrounds and theme avatars are downscaled to the screen resolution, the chat DOM stays small. Works with decorative themes such as Moonlit Echoes.',
        'perf.diagnose': 'Check performance',
        'perf.sectionInvisible': 'Invisible optimizations',
        'perf.offscreen': 'Do not render messages outside the screen',
        'perf.offscreenHint': 'The browser skips painting off-screen messages — including per-message blur, big theme avatars and shadows. Visible messages look exactly the same.',
        'perf.domLimit': 'Keep only the latest messages in the page',
        'perf.domLimitHint': 'While you are at the bottom of the chat, older rendered messages are removed from the page. "Show more messages" brings them back, just like after opening a chat.',
        'perf.domLimitCount': 'Messages to keep',
        'perf.optimizeImages': 'Downscale huge backgrounds and theme avatars',
        'perf.optimizeImagesHint': 'A 4K background or a 2048×3072 avatar takes 25–35 MB of memory each. They are resized to your screen resolution — the same picture on a phone, several times less memory. Animated images are left as they are. Files on disk are not changed.',
        'perf.imageQuality': 'Picture sharpness',
        'perf.qualityMax': 'Maximum (up to 3× screen density)',
        'perf.qualityHigh': 'High (2× — indistinguishable on phones)',
        'perf.qualityEco': 'Economy (1.25×)',
        'perf.lazyImages': 'Decode chat images in the background',
        'perf.sectionVisual': 'Tweaks that change the look',
        'perf.visualHint': 'Only for very weak phones — they change the design of the theme.',
        'perf.noBlur': 'Turn off blur everywhere (including the theme)',
        'perf.noAnimations': 'Turn off animations and transitions',
        'perf.noShadows': 'Turn off shadows',
        'perf.freezeAnimated': 'Freeze animated backgrounds and avatars',
        'perf.freezeAnimatedHint': 'Replaces an animated picture with its first frame (also downscaled).',
        'perf.sectionTavern': 'SillyTavern settings',
        'perf.tavernHint': 'Recommended values for phones. Nothing is changed until you press "Apply".',
        'perf.tweakTruncation': 'Messages loaded when a chat opens',
        'perf.tweakFps': 'Streaming updates per second',
        'perf.tweakSmooth': 'Smooth streaming',
        'perf.tweakMotion': 'Reduced motion',
        'perf.tweakFastUi': 'No-blur UI mode',
        'perf.tweakDone': 'Already optimal',
        'perf.changesLook': 'changes the look',
        'perf.apply': 'Apply',
        'perf.on': 'on',
        'perf.off': 'off',
        'perf.sectionServer': 'Server (Node.js / Termux)',
        'perf.serverHint': 'The server cannot be tuned from the browser. Run these commands in Termux (adjust the path if SillyTavern is not in ~/SillyTavern). Measured: Node memory 358 → 277 MB idle, 456 → 283 MB peak.',
        'perf.serverCommands': '# start SillyTavern with memory-saving Node.js flags\nbash ~/SillyTavern/data/default-user/extensions/st-extensionz/server/st-lite.sh\n\n# once: lighter config.yaml (a backup is kept)\nnode ~/SillyTavern/data/default-user/extensions/st-extensionz/server/apply-lite-config.mjs',
        'perf.diagTitle': 'Performance check',
        'perf.diagRunning': 'Measuring…',
        'perf.diagDom': 'Elements on the page',
        'perf.diagMessages': 'Messages in the page / in the chat',
        'perf.diagSkipped': 'Messages not rendered right now',
        'perf.diagBlur': 'Elements with blur',
        'perf.diagHeap': 'JavaScript memory',
        'perf.diagBg': 'Background',
        'perf.diagAvatar': 'Avatar',
        'perf.diagNotProcessed': 'not processed',
        'perf.diagAnimated': '{w}×{h}, animated — left as is',
        'perf.diagSmall': '{w}×{h}, already small enough',
        'perf.diagScaled': '{w}×{h} ({mb} MB) → {nw}×{nh} ({nmb} MB)',
        'perf.diagHint': 'Memory figures are for decoded pictures (width × height × 4 bytes).',

        // Folders
        'folders.moduleTitle': 'SillyTavern folders',
        'folders.desc': 'Quick access to SillyTavern data folders (characters, chats, backgrounds…) from the interface. In the Android app a folder opens right in the file manager; elsewhere its path is copied.',
        'folders.menu': 'SillyTavern folder',
        'folders.title': 'SillyTavern folders',
        'folders.open': 'Open',
        'folders.copyPath': 'Copy path',
        'folders.copied': 'Path copied: {path}',
        'folders.pathTitle': 'Folder path',
        'folders.openThis': 'Open the folder: {name}',
        'folders.panelButtons': 'Folder buttons in SillyTavern panels',
        'folders.panelButtonsHint': 'Adds a folder button next to "Import" in the character list, World Info, backgrounds and personas.',
        'folders.slashHelp': 'Opens a SillyTavern data folder. Argument: characters, chats, backgrounds, personas, worlds, … Without an argument shows the list.',
        'folders.hint.app': 'Tap "Open" to see the folder in the file manager. It is also in the system "Files" app → SillyTavern.',
        'folders.hint.termux': 'SillyTavern runs in Termux: the folders are inside ~/SillyTavern. In a file manager open the "Termux" section (the side menu of the "Files" app).',
        'folders.hint.desktop': 'The folders are on the computer where the SillyTavern server runs. Paths are relative to the SillyTavern folder.',
        'folders.root': 'All data',
        'folders.characters': 'Characters',
        'folders.chats': 'Chats',
        'folders.currentChat': 'Chats of the current character',
        'folders.groupChats': 'Group chats',
        'folders.backgrounds': 'Backgrounds',
        'folders.personas': 'Persona avatars',
        'folders.worlds': 'World Info (lorebooks)',
        'folders.images': 'Chat images',
        'folders.files': 'Attachments and Data Bank',
        'folders.themes': 'Themes',
        'folders.extensions': 'Extensions',
        'folders.backups': 'Backups',
    },

    ru: {
        'common.delete': 'Удалить',
        'common.resetDefaults': 'Сбросить по умолчанию',

        'core.intro': 'Набор удобных инструментов. Любой модуль можно отключить переключателем.',
        'core.language': 'Язык',
        'core.languageAuto': 'Автоматически',
        'core.enableModule': 'Включить / выключить модуль',

        // Panic
        'panic.title': 'Папа пришёл (режим паники)',
        'panic.desc': 'Одно нажатие — и картинки персонажей и фоны исчезают, а «интересные» предложения закрываются чёрными полосами, как в рассекреченных документах. Повторное нажатие возвращает всё как было. Сам чат не изменяется.',
        'panic.menuOn': 'Папа пришёл!',
        'panic.menuOff': 'Отбой — вернуть всё',
        'panic.toggleNow': 'Переключить сейчас',
        'panic.sectionTriggers': 'Как включать',
        'panic.hotkey': 'Горячая клавиша',
        'panic.hotkeyHint': 'Нажмите на поле и затем сочетание клавиш. Работает на любой раскладке.',
        'panic.hotkeyPlaceholder': 'Нажмите и введите сочетание',
        'panic.doubleEscape': 'Двойное нажатие Esc',
        'panic.floatingButton': 'Плавающая кнопка',
        'panic.floatingButtonHint': 'Маленькая кнопка поверх страницы — самый быстрый способ на телефоне. Её можно перетащить куда угодно.',
        'panic.threeFingerTap': 'Касание тремя пальцами (сенсорные экраны)',
        'panic.threeFingerTapHint': 'Коснитесь экрана тремя пальцами одновременно.',
        'panic.rememberState': 'Оставаться скрытым после перезагрузки',
        'panic.rememberStateHint': 'Если страницу перезагрузят в скрытом режиме, она откроется скрытой.',
        'panic.sectionImages': 'Картинки',
        'panic.hideImages': 'Скрывать аватарки, спрайты и картинки в чате',
        'panic.hideBackground': 'Скрывать фон чата',
        'panic.imageMode': 'Как скрывать',
        'panic.imageModeHide': 'Убирать полностью (нейтральная заглушка)',
        'panic.imageModeBlur': 'Сильно размывать',
        'panic.hidePanels': 'Прятать открытые боковые панели',
        'panic.hidePanelsHint': 'Список персонажей, карточка, World Info, плавающие окна. Потом вернутся ровно как были.',
        'panic.sectionText': 'Цензура текста',
        'panic.redactText': 'Закрашивать найденный текст',
        'panic.redactMode': 'Что закрашивать',
        'panic.modeSentence': 'Всё предложение с ключевым словом',
        'panic.modeWord': 'Только само слово',
        'panic.modeParagraph': 'Весь абзац',
        'panic.keywords': 'Ключевые слова',
        'panic.keywordsHint': 'По одному в строке или через запятую. слово — само слово и его формы; слово* — всё, что начинается так; "слово" — строго это слово; несколько слов — фраза; /регулярка/ — регулярное выражение; # — комментарий.',
        'panic.keywordsCount': 'Активных записей: {count}',
        'panic.keywordsErrors': 'Активных записей: {count}. С ошибкой: {errors}',
        'panic.smartForms': 'Автоматически учитывать формы слов',
        'panic.smartFormsHint': 'поцелуй найдёт и поцелуя / поцелуями, kiss — kisses / kissed.',
        'panic.redactReasoning': 'Закрашивать и блоки размышлений (reasoning)',
        'panic.redactNames': 'Закрашивать имена персонажей и персоны',
        'panic.redactNamesHint': 'Имена в тексте и в заголовках сообщений тоже станут чёрными полосами.',
        'panic.noise': 'Дополнительная случайная цензура',
        'panic.noiseHint': 'Закрашивать ещё и часть обычных предложений — страница выглядит как настоящий рассекреченный файл, а контекст сложнее угадать.',
        'panic.barColor': 'Цвет полос',
        'panic.peekOnHold': 'Подсмотреть, зажав полосу',
        'panic.peekOnHoldHint': 'Текст виден, только пока вы держите на нём палец или кнопку мыши.',
        'panic.sectionExtras': 'Дополнительно',
        'panic.blurInput': 'Размывать поле ввода',
        'panic.pauseMedia': 'Ставить на паузу музыку, видео и озвучку (и продолжать потом)',
        'panic.stopGeneration': 'Останавливать генерацию',
        'panic.disguiseTab': 'Маскировать вкладку браузера (название и иконка)',
        'panic.disguiseTitle': 'Название вкладки в скрытом режиме',
        'panic.defaultTitle': 'Документ без названия',
        'panic.slashHelp': 'Переключает режим «Папа пришёл». Аргумент: on, off или toggle.',

        // Navigator
        'nav.title': 'Поиск по чату и закладки',
        'nav.desc': 'Поиск по всему чату, включая старые незагруженные сообщения и альтернативные свайпы. Закладки на важные сообщения и переход к ним в одно касание.',
        'nav.menuSearch': 'Поиск по чату',
        'nav.menuPins': 'Закладки',
        'nav.searchTitle': 'Поиск по чату',
        'nav.searchPlaceholder': 'Слова или "точная фраза"…',
        'nav.searchHint': 'Начните вводить — поиск идёт по всем {count} сообщениям. Несколько слов — должны встретиться все.',
        'nav.filter.all': 'Все',
        'nav.filter.user': 'Мои',
        'nav.filter.char': 'Персонаж',
        'nav.wholeWords': 'Целые слова',
        'nav.includeSwipes': 'Свайпы',
        'nav.includeReasoning': 'Размышления',
        'nav.found': 'Найдено: {total}',
        'nav.foundMore': 'Найдено: {total} (показано {shown})',
        'nav.nothing': 'Ничего не найдено',
        'nav.swipeOf': 'свайп {n}/{total}',
        'nav.reasoning': 'размышления',
        'nav.swipeHint': 'Совпадение — в свайпе №{n} этого сообщения.',
        'nav.toTop': 'В начало',
        'nav.toBottom': 'В конец',
        'nav.goto': 'Перейти',
        'nav.gotoInvalid': 'Введите номер сообщения от 0 до {max}.',
        'nav.searchHotkey': 'Горячая клавиша поиска',
        'nav.showMessageButton': 'Кнопка закладки на сообщениях',
        'nav.showMessageButtonHint': 'Кнопка ☆ появится в действиях сообщения (меню «…»).',
        'nav.pinButton': 'В закладки',
        'nav.pinsTitle': 'Закладки в этом чате',
        'nav.pinsCount': 'Закладок: {count}',
        'nav.pinsEmpty': 'Закладок пока нет. Нажмите ☆ в действиях сообщения или кнопку ниже.',
        'nav.pinsHint': 'Закладки хранятся в самом файле чата и не сбиваются, даже если удалить сообщения выше.',
        'nav.pinLast': 'В закладки последнее сообщение',
        'nav.pinNotePlaceholder': 'Заметка…',
        'nav.pinBroken': 'Сообщение не найдено (удалено?)',
        'nav.pinAdded': 'Сообщение #{id} в закладках',
        'nav.pinRemoved': 'Закладка #{id} удалена',
        'nav.slashSearch': 'Открывает поиск по чату. Необязательный аргумент — запрос.',
        'nav.slashPin': 'Ставит или снимает закладку. Аргумент — номер сообщения (по умолчанию последнее).',
        'nav.slashPins': 'Открывает список закладок текущего чата.',

        // Drafts
        'drafts.title': 'Черновики и история ввода',
        'drafts.desc': 'Набираемый текст сохраняется для каждого чата и переживает перезагрузку, закрытие вкладки и переключение чатов. Отправленные сообщения попадают в историю, откуда их можно вернуть.',
        'drafts.menu': 'История ввода',
        'drafts.restored': 'Черновик восстановлен',
        'drafts.perChat': 'Отдельный черновик для каждого чата',
        'drafts.perChatHint': 'При переключении чатов в поле ввода появляется черновик открытого чата.',
        'drafts.notifyRestore': 'Сообщать о восстановлении черновика',
        'drafts.historyHotkeys': 'Alt + ↑ / ↓ листает отправленные сообщения',
        'drafts.historyHotkeysHint': 'Работает в поле ввода, как история команд в терминале.',
        'drafts.historySize': 'Размер истории',
        'drafts.historyTitle': 'История ввода',
        'drafts.historyHint': 'Нажмите на запись, чтобы вставить её в поле ввода.',
        'drafts.lastDraft': 'Последний черновик этого чата',
        'drafts.lastDraftMeta': 'Верните, если случайно стёрли',
        'drafts.sent': 'Отправленные ({count})',
        'drafts.empty': 'Пока пусто.',
        'drafts.clearHistory': 'Очистить историю',
        'drafts.slashHelp': 'Открывает историю ввода.',

        // Slop radar
        'slop.title': 'Детектор клише',
        'slop.desc': 'Подчёркивает заезженные нейросетевые фразы («мурашки по коже», «голос, едва громче шёпота», «ozone»…) в ответах, считает их по чату и может попросить модель избегать тех, что она повторяет чаще всего.',
        'slop.menu': 'Детектор клише',
        'slop.markTitle': 'Клише',
        'slop.highlight': 'Подчёркивать клише в ответах',
        'slop.style': 'Стиль',
        'slop.styleWavy': 'Волнистое подчёркивание',
        'slop.styleDotted': 'Пунктир',
        'slop.styleBackground': 'Маркер (фон)',
        'slop.color': 'Цвет',
        'slop.phrases': 'Фразы',
        'slop.phrasesHint': 'Тот же синтаксис, что у ключевых слов: слово, слово*, "точно", фразы и /регулярки/.',
        'slop.phrasesCount': 'Активных записей: {count}',
        'slop.phrasesErrors': 'Активных записей: {count}. С ошибкой: {errors}',
        'slop.sectionInject': 'Инструкция против клише',
        'slop.injectAvoid': 'Автоматически просить модель избегать её частых клише',
        'slop.injectAvoidHint': 'Добавляет в промпт короткую системную заметку с самыми частыми клише этого чата. Обновляется после каждого ответа.',
        'slop.injectTop': 'Сколько фраз включать',
        'slop.injectScope': 'Анализировать последние N ответов',
        'slop.injectDepth': 'Глубина вставки (0 = в самом конце)',
        'slop.injectTemplate': 'Шаблон инструкции',
        'slop.injectTemplateHint': '{phrases} заменяется списком фраз.',
        'slop.statsTitle': 'Детектор клише — этот чат',
        'slop.kpiIndex': 'на 1000 слов',
        'slop.kpiIndexHint': 'Клише на 1000 слов в ответах ИИ',
        'slop.kpiHits': 'клише',
        'slop.kpiMessages': 'ответов',
        'slop.kpiWords': 'слов',
        'slop.gradeClean': 'Чистый текст — красота!',
        'slop.gradeOk': 'Терпимо',
        'slop.gradeMany': 'Клише многовато',
        'slop.gradeSlop': 'Сплошной слоп!',
        'slop.gradeTooLittle': 'Пока слишком мало текста для оценки',
        'slop.chartTitle': 'Клише в последних ответах (нажмите на столбик, чтобы перейти)',
        'slop.topTitle': 'Чаще всего',
        'slop.noHits': 'Клише не найдено.',
        'slop.copyInstruction': 'Скопировать как инструкцию',
        'slop.copied': 'Скопировано — вставьте в Author\'s Note или системный промпт.',
        'slop.statsHint': 'Учитываются только ответы ИИ. Список фраз редактируется в настройках расширения.',
        'slop.slashHelp': 'Открывает статистику клише текущего чата и возвращает число клише на 1000 слов.',

        // Notifier
        'notifier.title': 'Уведомления об ответе и «не гасить экран»',
        'notifier.desc': 'Звук, вибрация или мигающая вкладка, когда ответ готов. А пока модель пишет, экран не гаснет — телефон не уснёт и не оборвёт генерацию.',
        'notifier.readyTitle': '{name}: ответ готов',
        'notifier.readyBody': 'Откройте чат, чтобы прочитать',
        'notifier.test': 'Проверить',
        'notifier.onlyWhenHidden': 'Только когда вкладка в фоне',
        'notifier.onlyWhenHiddenHint': 'Иначе — после каждого ответа.',
        'notifier.sound': 'Звук',
        'notifier.volume': 'Громкость',
        'notifier.vibrate': 'Вибрация',
        'notifier.vibrateHint': 'Только телефоны; браузер вибрирует, лишь пока страница на экране.',
        'notifier.flashTitle': 'Мигать названием вкладки',
        'notifier.systemNotification': 'Системное уведомление',
        'notifier.systemNotificationHint': 'Попросит разрешение. Работает в браузерах на ПК; Chrome на Android может не показать его без установленного приложения.',
        'notifier.showPreview': 'Показывать текст ответа в уведомлении',
        'notifier.minDuration': 'Минимальное время генерации, сек',
        'notifier.minDurationHint': 'Быстрые ответы не вызывают уведомление.',
        'notifier.sectionWake': 'Не гасить экран',
        'notifier.wakeLock': 'Блокировка сна экрана',
        'notifier.wakeGeneration': 'Пока генерируется ответ',
        'notifier.wakeAlways': 'Всегда, пока открыта вкладка',
        'notifier.wakeOff': 'Выключено',
        'notifier.wakeHint': 'Нужен HTTPS или localhost / 127.0.0.1.',
        'notifier.wakeUnsupported': 'Этот браузер не поддерживает Wake Lock.',

        // Performance
        'perf.title': 'Оптимизация (телефон)',
        'perf.desc': 'Облегчает таверну на телефоне, не меняя внешний вид: сообщения за экраном не рисуются, огромные фоны и аватарки темы уменьшаются до разрешения экрана, страница не разрастается. Дружит с декоративными темами вроде Moonlit Echoes.',
        'perf.diagnose': 'Проверить производительность',
        'perf.sectionInvisible': 'Незаметные оптимизации',
        'perf.offscreen': 'Не рисовать сообщения за пределами экрана',
        'perf.offscreenHint': 'Браузер пропускает отрисовку сообщений вне экрана — вместе с размытием под каждым сообщением, большими аватарками темы и тенями. Видимые сообщения выглядят точно так же.',
        'perf.domLimit': 'Держать на странице только последние сообщения',
        'perf.domLimitHint': 'Пока вы внизу чата, старые отрисованные сообщения убираются со страницы. Кнопка «Show more messages» возвращает их — как после открытия чата.',
        'perf.domLimitCount': 'Сколько сообщений держать',
        'perf.optimizeImages': 'Уменьшать огромные фоны и аватарки темы',
        'perf.optimizeImagesHint': 'Фон 4K или аватарка 2048×3072 занимают 25–35 МБ памяти каждая. Они уменьшаются до разрешения экрана — на телефоне картинка та же, памяти в разы меньше. Анимированные картинки не трогаются. Файлы на диске не меняются.',
        'perf.imageQuality': 'Чёткость картинок',
        'perf.qualityMax': 'Максимальная (до 3× плотности экрана)',
        'perf.qualityHigh': 'Высокая (2× — на телефоне не отличить)',
        'perf.qualityEco': 'Экономная (1,25×)',
        'perf.lazyImages': 'Декодировать картинки в чате в фоне',
        'perf.sectionVisual': 'Меняют внешний вид',
        'perf.visualHint': 'Только для совсем слабых телефонов — эти опции меняют дизайн темы.',
        'perf.noBlur': 'Отключить размытие везде (и в теме)',
        'perf.noAnimations': 'Отключить анимации и переходы',
        'perf.noShadows': 'Отключить тени',
        'perf.freezeAnimated': 'Замораживать анимированные фоны и аватарки',
        'perf.freezeAnimatedHint': 'Анимированная картинка заменяется первым кадром (тоже уменьшенным).',
        'perf.sectionTavern': 'Настройки таверны',
        'perf.tavernHint': 'Рекомендуемые значения для телефона. Ничего не меняется, пока не нажмёте «Применить».',
        'perf.tweakTruncation': 'Сообщений при открытии чата',
        'perf.tweakFps': 'Обновлений в секунду при стриминге',
        'perf.tweakSmooth': 'Плавный стриминг',
        'perf.tweakMotion': 'Меньше анимаций',
        'perf.tweakFastUi': 'Режим без размытия',
        'perf.tweakDone': 'Уже оптимально',
        'perf.changesLook': 'меняет вид',
        'perf.apply': 'Применить',
        'perf.on': 'вкл',
        'perf.off': 'выкл',
        'perf.sectionServer': 'Сервер (Node.js / Termux)',
        'perf.serverHint': 'Сервер из браузера не настроить — выполните команды в Termux (поправьте путь, если таверна не в ~/SillyTavern). Замер: память Node 358 → 277 МБ в простое, 456 → 283 МБ в пике.',
        'perf.serverCommands': '# запуск таверны с экономией памяти Node.js\nbash ~/SillyTavern/data/default-user/extensions/st-extensionz/server/st-lite.sh\n\n# один раз: облегчённый config.yaml (резервная копия сохраняется)\nnode ~/SillyTavern/data/default-user/extensions/st-extensionz/server/apply-lite-config.mjs',
        'perf.diagTitle': 'Проверка производительности',
        'perf.diagRunning': 'Измеряю…',
        'perf.diagDom': 'Элементов на странице',
        'perf.diagMessages': 'Сообщений на странице / в чате',
        'perf.diagSkipped': 'Сейчас не рисуется сообщений',
        'perf.diagBlur': 'Элементов с размытием',
        'perf.diagHeap': 'Память JavaScript',
        'perf.diagBg': 'Фон',
        'perf.diagAvatar': 'Аватарка',
        'perf.diagNotProcessed': 'не обработан',
        'perf.diagAnimated': '{w}×{h}, анимированный — оставлен как есть',
        'perf.diagSmall': '{w}×{h}, уже достаточно маленький',
        'perf.diagScaled': '{w}×{h} ({mb} МБ) → {nw}×{nh} ({nmb} МБ)',
        'perf.diagHint': 'Память указана для раскодированных картинок (ширина × высота × 4 байта).',

        // Folders
        'folders.moduleTitle': 'Папки SillyTavern',
        'folders.desc': 'Быстрый доступ к папкам таверны (персонажи, чаты, фоны…) прямо из интерфейса. В приложении для Android папка открывается в файловом менеджере, в остальных случаях копируется путь.',
        'folders.menu': 'Папка SillyTavern',
        'folders.title': 'Папки SillyTavern',
        'folders.open': 'Открыть',
        'folders.copyPath': 'Скопировать путь',
        'folders.copied': 'Путь скопирован: {path}',
        'folders.pathTitle': 'Путь к папке',
        'folders.openThis': 'Открыть папку: {name}',
        'folders.panelButtons': 'Кнопки папок в панелях таверны',
        'folders.panelButtonsHint': 'Кнопка с папкой рядом с «Импортом» в списке персонажей, World Info, фонах и персонах.',
        'folders.slashHelp': 'Открывает папку данных таверны. Аргумент: characters, chats, backgrounds, personas, worlds, … Без аргумента показывает список.',
        'folders.hint.app': 'Нажмите «Открыть», чтобы увидеть папку в файловом менеджере. Она же есть в системном приложении «Файлы» → SillyTavern.',
        'folders.hint.termux': 'Таверна запущена в Termux: папки лежат внутри ~/SillyTavern. В файловом менеджере откройте раздел «Termux» (боковое меню приложения «Файлы»).',
        'folders.hint.desktop': 'Папки находятся на компьютере, где запущен сервер таверны. Пути указаны относительно папки SillyTavern.',
        'folders.root': 'Все данные',
        'folders.characters': 'Персонажи',
        'folders.chats': 'Чаты',
        'folders.currentChat': 'Чаты текущего персонажа',
        'folders.groupChats': 'Групповые чаты',
        'folders.backgrounds': 'Фоны',
        'folders.personas': 'Аватарки персон',
        'folders.worlds': 'World Info (лорбуки)',
        'folders.images': 'Картинки из чатов',
        'folders.files': 'Вложения и Data Bank',
        'folders.themes': 'Темы',
        'folders.extensions': 'Расширения',
        'folders.backups': 'Бэкапы',
    },
};
